name: figma_exporter
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/lizeWrk/figma_exporter_lz

environment:
  sdk: ">=2.19.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  generate_colors: generateColors.dart
