name: figma_exporter
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/lizeWrk/figma_exporter_lz

scripts:
  "activate:global": dart pub global activate --source path .
  "deactivate:global": dart pub global deactivate figma_exporter
  "list:global": dart pub global list

environment:
  sdk: ">=2.19.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  # generate_colors: generateColors.dart
  generate_enums_colors: generate_enums_colors.dart
